<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

// TODO : see what we can do with http://domain.com:9000/admin/profileinfo/

function d4os_ui_profile_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os_ui_profiles':
      return '<p>' . t('OpenSim grid profiles management') . '</p>';
  }
}

function d4os_ui_profile_menu() {
  $items['user/%/grid/profile'] = array(
    'title'             => 'Profile',
    'description'       => 'Grid profile.',
    'page callback'     => 'd4os_ui_profile_display_public_profile',
    'page arguments'    => array(1),
    'type'              => MENU_NORMAL_ITEM,
    'access callback'   => TRUE,
  );
  
  $items['admin/settings/d4os/ui/profile'] = array(
    'title'             => 'profile',
    'description'       => 'd4os ui profile settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_ui_profile_admin'),
    'access arguments'  => array('admin d4os ui profile'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os_ui_profile.admin.inc'
   );
  return $items;
}

function d4os_ui_profile_perm() {
  return array(
    'admin d4os ui profile',
    'access d4os ui profile'
  );
}

function d4os_ui_profile_display_public_profile($uid) {
  return "coucou";
}