<?php
/**
 * @package   d4os_main
 * @copyright Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @link      http://www.d4os.org
 * @license   GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

module_load_include('helpers.inc', 'd4os');

function d4os_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os':
      return '<p>' . t('OpenSim grid management') . '</p>';
  }
}

function d4os_menu() {
  $items = array();
  $items['admin/settings/d4os'] = array(
    'title'             => 'd4os settings',
    'description'       => 'd4os settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_admin'),
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/io'] = array(
    'title'             => 'IO',
    'description'       => 'IO settings',
    'page callback'     => 'd4os_admin_io',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/io/services'] = array(
    'title'             => 'services',
    'description'       => 'services settings',
    'page callback'     => 'd4os_admin_services',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/ui'] = array(
    'title'             => 'UI',
    'description'       => 'UI settings',
    'page callback'     => 'd4os_admin_ui',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/ui/grid/monitor'] = array(
    'title'             => 'Grid monitor',
    'description'       => 'UI grid monitor settings',
    'page callback'     => 'd4os_admin_ui_grid_monitor',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  return $items;
}

function d4os_perm() {
  return array(
    'admin d4os',
  );
}
