<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

module_load_include('helpers.inc', 'd4os');

define('UUID_ZERO', '00000000-0000-0000-0000-000000000000');
global $grid_url;
global $base_url;
$grid_uri   = variable_get('d4os_default_grid_uri', $base_url);
$grid_port  = variable_get('d4os_default_grid_port', '9000');
$grid_url   = $grid_uri. ':'. $grid_port;

function d4os_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os':
      return '<p>' . t('OpenSim grid management') . '</p>';
  }
}

function d4os_menu() {
  $items = array();
  $items['admin/settings/d4os'] = array(
    'title'             => t('d4os settings'),
    'description'       => t('d4os settings'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_admin'),
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/io'] = array(
    'title'             => t('IO'),
    'description'       => t('IO settings'),
    'page callback'     => 'd4os_admin_io',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/io/services'] = array(
    'title'             => t('services'),
    'description'       => t('services settings'),
    'page callback'     => 'd4os_admin_services',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  $items['admin/settings/d4os/ui'] = array(
    'title'             => t('UI'),
    'description'       => t('UI settings'),
    'page callback'     => 'd4os_admin_ui',
    'access arguments'  => array('admin d4os'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os.admin.inc'
  );
  return $items;
}

function d4os_perm() {
  return array(
    'admin d4os',
  );
}