<?php
/**
 * @package    d4os_io_radmin
 * @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

/**
 * Hook help
 */
function d4os_io_radmin_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os':
      return '<p>' . t('OpenSim grid management') . '</p>';
  }
}

function d4os_io_radmin_menu() {
  $items = array();
  $items['admin/settings/d4os/io/radmin'] = array(
    'title'             => 'radmin',
    'description'       => 'd4os io radmin settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_radmin_admin'),
    'access arguments'  => array('admin d4os radmin'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os_io_radmin.admin.inc'
   );
  $items['grid/radmin'] = array(
    'title'             => 'Radmin',
    'description'       => 'd4os radmin',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_radmin_form'),
    'access arguments'  => array('access d4os radmin'),
    'type'              => MENU_NORMAL_ITEM,
   );
  // ahah
  $items['grid/radmin/%/js'] = array(
    'page callback'     => 'd4os_io_radmin_js',
    'page arguments'    => array(2),
    'access arguments'  => array('access d4os radmin'),
    'type '             => MENU_CALLBACK,
  );
  return $items;
}

function d4os_io_radmin_perm() {
  return array(
    'admin d4os radmin',
    'access d4os radmin'
  );
}

function d4os_io_radmin_form() {
  $form = array();
  d4os_io_radmin_regions_form($form);
  d4os_io_radmin_users_form($form);
  d4os_io_radmin_region_state_form($form);
  d4os_io_radmin_acl_form($form);
  return $form;
}

function d4os_io_radmin_regions_form(&$form) {
  $form['d4os_io_radmin']['regions'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Regions'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  // admin_create_region
  $form['d4os_io_radmin']['regions']['admin_create_region'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_create_region',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Create a new region'),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t("Region name."),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_id'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region id'),
    '#description'  => t("Region id (optional)."),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_master_first'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Master firstname'),
    '#description'  => t("Master firstname"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_master_last'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Master lastname'),
    '#description'  => t("Master lastname"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_master_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Master uuid'),
    '#description'  => t("Master uuid (optional)"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_master_password'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Master password'),
    '#description'  => t("Master password"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_listen_ip'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Listen IP'),
    '#description'  => t("Listen IP"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_listen_port'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Listen port'),
    '#description'  => t("Listen port"),
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_external_address'] = array(
    '#type'         => 'textfield',
    '#title'        => t('External address'),
    '#description'  => t("External address"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_x'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region X'),
    '#description'  => t("Region X"),
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_region_Y'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region Y'),
    '#description'  => t("Region Y"),
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_persist'] = array(
    '#type'         => 'checkbox',
    '#title'        => t('Persist'),
    '#description'  => t("Persist"),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_public'] = array(
    '#type'         => 'checkbox',
    '#title'        => t('Public'),
    '#description'  => t('Public'),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_enable_voice'] = array(
    '#type'         => 'checkbox',
    '#title'        => t('Enable voice'),
    '#description'  => t('Enable voice'),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_create_region/js',
      'wrapper' => 'd4os-radmin-admin-create-region-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_create_region']['d4os_io_radmin_admin_create_region_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-create-region-output">',
    '#suffix' => '</div>',
  );
// admin_delete_region
  $form['d4os_io_radmin']['regions']['admin_delete_region'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_delete_region',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Delete a region'),
  );
  $form['d4os_io_radmin']['regions']['admin_delete_region']['d4os_io_radmin_admin_delete_region_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['regions']['admin_delete_region']['d4os_io_radmin_admin_delete_region_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_delete_region/js',
      'wrapper' => 'd4os-radmin-admin-delete-region-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_delete_region']['d4os_io_radmin_admin_delete_region_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-delete-region-output">',
    '#suffix' => '</div>',
  );
// TODO : close region
// admin_modify_region
  $form['d4os_io_radmin']['regions']['admin_modify_region'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_modify_region',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Modify a region'),
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_public'] = array(
    '#type'         => 'checkbox',
    '#title'        => t('Public'),
    '#description'  => t('Public'),
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_enable_voice'] = array(
    '#type'         => 'checkbox',
    '#title'        => t('Enable voice'),
    '#description'  => t('Enable voice'),
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_modify_region/js',
      'wrapper' => 'd4os-radmin-admin-modify-region-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_modify_region']['d4os_io_radmin_admin_modify_region_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-modify-region-output">',
    '#suffix' => '</div>',
  );
// admin_region_query
  $form['d4os_io_radmin']['regions']['admin_region_query'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_region_query',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Query the "health" of a region'),
  );
  $form['d4os_io_radmin']['regions']['admin_region_query']['d4os_io_radmin_admin_region_query_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['regions']['admin_region_query']['d4os_io_radmin_admin_region_query_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['regions']['admin_region_query']['d4os_io_radmin_admin_region_query_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_region_query/js',
      'wrapper' => 'd4os-radmin-admin-region-query-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_region_query']['d4os_io_radmin_admin_region_query_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-region-query-output">',
    '#suffix' => '</div>',
  );
// admin_shutdown
  $form['d4os_io_radmin']['regions']['admin_shutdown'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_shutdown',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Shut down the simulator'),
  );
  $form['d4os_io_radmin']['regions']['admin_shutdown']['d4os_io_radmin_admin_shutdown_delayed'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Delay'),
    '#description'  => t('Delay in seconds (optional)'),
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['regions']['admin_shutdown']['d4os_io_radmin_admin_shutdown_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_shutdown/js',
      'wrapper' => 'd4os-radmin-admin-shutdown-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_shutdown']['d4os_io_radmin_admin_shutdown_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-shutdown-output">',
    '#suffix' => '</div>',
  );
// admin_broadcast
  $form['d4os_io_radmin']['regions']['admin_broadcast'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_broadcast',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Send a general alert'),
  );
  $form['d4os_io_radmin']['regions']['admin_broadcast']['d4os_io_radmin_admin_broadcast_message'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Message'),
    '#description'  => t("Message."),
  );
  $form['d4os_io_radmin']['regions']['admin_broadcast']['d4os_io_radmin_admin_broadcast_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_broadcast/js',
      'wrapper' => 'd4os-radmin-admin-broadcast-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_broadcast']['d4os_io_radmin_admin_broadcast_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-broadcast-output">',
    '#suffix' => '</div>',
  );
// admin_restart
  $form['d4os_io_radmin']['regions']['admin_restart'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_restart',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Restart Region'),
  );
  $form['d4os_io_radmin']['regions']['admin_restart']['d4os_io_radmin_admin_restart_regionID'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region id'),
    '#description'  => t('Region id'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['regions']['admin_restart']['d4os_io_radmin_admin_restart_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_restart/js',
      'wrapper' => 'd4os-radmin-admin-restart-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_restart']['d4os_io_radmin_admin_restart_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-restart-output">',
    '#suffix' => '</div>',
  );
// admin_load_heightmap
  $form['d4os_io_radmin']['regions']['admin_load_heightmap'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_load_heightmap',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Load Height Map'),
  );
  $form['d4os_io_radmin']['regions']['admin_load_heightmap']['d4os_io_radmin_admin_load_heightmap_filename'] = array(
    '#type'         => 'textfield',
    '#title'        => t('File name'),
    '#description'  => t('File name'),
  );
  $form['d4os_io_radmin']['regions']['admin_load_heightmap']['d4os_io_radmin_admin_load_heightmap_regionid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region id'),
    '#description'  => t('Region id'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['regions']['admin_load_heightmap']['d4os_io_radmin_admin_load_heightmap_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_load_heightmap/js',
      'wrapper' => 'd4os-radmin-admin-load-heightmap-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['regions']['admin_load_heightmap']['d4os_io_radmin_admin_load_heightmap_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-load-heightmap-output">',
    '#suffix' => '</div>',
  );
  
}

function d4os_io_radmin_users_form(&$form) {
  $form['d4os_io_radmin']['users'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Users'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
// admin_create_user
  $form['d4os_io_radmin']['users']['admin_create_user'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_create_user',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Create a new user'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_user_firstname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User firstname'),
    '#description'  => t('User firstname'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_user_lastname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User lastname'),
    '#description'  => t('User lastname'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_user_password'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User password'),
    '#description'  => t('User password'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_start_region_x'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region X'),
    '#description'  => t('Start region X'),
    //'#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_start_region_y'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region Y'),
    '#description'  => t('Start region Y'),
    //'#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_create_user/js',
      'wrapper' => 'd4os-radmin-admin-create-user-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['users']['admin_create_user']['d4os_io_radmin_admin_create_user_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-create-user-output">',
    '#suffix' => '</div>',
  );
  
// admin_create_user_email
  $form['d4os_io_radmin']['users']['admin_create_user_email'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_create_user_email',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Create a new user (alias for admin_create_user)'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_user_firstname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User firstname'),
    '#description'  => t('User firstname'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_user_lastname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User lastname'),
    '#description'  => t('User lastname'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_user_password'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User password'),
    '#description'  => t('User password'),
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_start_region_x'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region X'),
    '#description'  => t('Start region X'),
    //'#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_start_region_y'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region Y'),
    '#description'  => t('Start region Y'),
    //'#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_create_user_email/js',
      'wrapper' => 'd4os-radmin-admin-create-user-email-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['users']['admin_create_user_email']['d4os_io_radmin_admin_create_user_email_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-create-user-email-output">',
    '#suffix' => '</div>',
  );
// admin_exists_user
  $form['d4os_io_radmin']['users']['admin_exists_user'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_exists_user',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Check whether a certain user account exists'),
  );
  $form['d4os_io_radmin']['users']['admin_exists_user']['d4os_io_radmin_admin_exists_user_user_firstname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User firstname'),
    '#description'  => t('User firstname'),
  );
  $form['d4os_io_radmin']['users']['admin_exists_user']['d4os_io_radmin_admin_exists_user_user_lastname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User lastname'),
    '#description'  => t('User lastname'),
  );
  $form['d4os_io_radmin']['users']['admin_exists_user']['d4os_io_radmin_admin_exists_user_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_exists_user/js',
      'wrapper' => 'd4os-radmin-admin-exists-user-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['users']['admin_exists_user']['d4os_io_radmin_admin_exists_user_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-exists-user-output">',
    '#suffix' => '</div>',
  );
// admin_update_user
  $form['d4os_io_radmin']['users']['admin_update_user'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_update_user',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Update the password/home of a user account'),
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_user_firstname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User firstname'),
    '#description'  => t('User firstname'),
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_user_lastname'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User lastname'),
    '#description'  => t('User lastname'),
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_user_password'] = array(
    '#type'         => 'textfield',
    '#title'        => t('User password'),
    '#description'  => t('User password'),
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_start_region_x'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region X'),
    '#description'  => t('Start region X'),
    '#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_start_region_y'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Start region Y'),
    '#description'  => t('Start region Y'),
    '#default_value'=> 1000,
    '#size'         => 5,
    '#maxlength'    => 5,
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_update_user/js',
      'wrapper' => 'd4os-radmin-admin-update-user-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['users']['admin_update_user']['d4os_io_radmin_admin_update_user_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-update-user-output">',
    '#suffix' => '</div>',
  );

}

function d4os_io_radmin_region_state_form(&$form) {
  $form['d4os_io_radmin']['region_state'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Region state'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
// admin_load_xml
  $form['d4os_io_radmin']['region_state']['admin_load_xml'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_load_xml',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Execute the Load XML command'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_filename'] = array(
    '#type'         => 'textfield',
    '#title'        => t('File name'),
    '#description'  => t('File name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_xml_version'] = array(
    '#type'         => 'select',
    '#options'      => array('1' => '1', '2' => '2'),
    '#title'        => t('XML version'),
    '#description'  => t('XML version'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_load_xml/js',
      'wrapper' => 'd4os-radmin-admin-load-xml-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_xml']['d4os_io_radmin_admin_load_xml_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-load-xml-output">',
    '#suffix' => '</div>',
  );
// admin_save_xml
  $form['d4os_io_radmin']['region_state']['admin_save_xml'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_save_xml',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Execute the Save XML command'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_filename'] = array(
    '#type'         => 'textfield',
    '#title'        => t('File name'),
    '#description'  => t('File name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_xml_version'] = array(
    '#type'         => 'select',
    '#options'      => array('1' => '1', '2' => '2'),
    '#title'        => t('XML version'),
    '#description'  => t('XML version'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_save_xml/js',
      'wrapper' => 'd4os-radmin-admin-save-xml-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_xml']['d4os_io_radmin_admin_save_xml_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-save-xml-output">',
    '#suffix' => '</div>',
  );
// admin_load_oar
  $form['d4os_io_radmin']['region_state']['admin_load_oar'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_load_oar',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Load a saved OAR file into a region'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_oar']['d4os_io_radmin_admin_load_oar_filename'] = array(
    '#type'         => 'textfield',
    '#title'        => t('File name'),
    '#description'  => t('File name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_oar']['d4os_io_radmin_admin_load_oar_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_oar']['d4os_io_radmin_admin_load_oar_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['region_state']['admin_load_oar']['d4os_io_radmin_admin_load_oar_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_load_oar/js',
      'wrapper' => 'd4os-radmin-admin-load-oar-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['region_state']['admin_load_oar']['d4os_io_radmin_admin_load_oar_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-load-oar-output">',
    '#suffix' => '</div>',
  );
// admin_save_oar
  $form['d4os_io_radmin']['region_state']['admin_save_oar'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_save_oar',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Saved an OAR file of a regions contents'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_oar']['d4os_io_radmin_admin_save_oar_filename'] = array(
    '#type'         => 'textfield',
    '#title'        => t('File name'),
    '#description'  => t('File name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_oar']['d4os_io_radmin_admin_save_oar_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t('Region name'),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_oar']['d4os_io_radmin_admin_save_oar_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['region_state']['admin_save_oar']['d4os_io_radmin_admin_save_oar_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_save_oar/js',
      'wrapper' => 'd4os-radmin-admin-save-oar-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['region_state']['admin_save_oar']['d4os_io_radmin_admin_save_oar_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-save-oar-output">',
    '#suffix' => '</div>',
  );

}

function d4os_io_radmin_acl_form(&$form) {
  $form['d4os_io_radmin']['acl'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Acl'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
// admin_acl_clear
  $form['d4os_io_radmin']['acl']['admin_acl_clear'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_acl_clear',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Clear the access list for the region'),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_clear']['d4os_io_radmin_admin_acl_clear_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t("Region name."),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_clear']['d4os_io_radmin_admin_acl_clear_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['acl']['admin_acl_clear']['d4os_io_radmin_admin_acl_clear_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_acl_clear/js',
      'wrapper' => 'd4os-radmin-admin-acl-clear-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_clear']['d4os_io_radmin_admin_acl_clear_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-acl-clear-output">',
    '#suffix' => '</div>',
  );
// admin_acl_add
  $form['d4os_io_radmin']['acl']['admin_acl_add'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_acl_add',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Add a list of users to the access control list'),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_add']['d4os_io_radmin_admin_acl_add_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region'),
    '#description'  => t("Region name."),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_add']['d4os_io_radmin_admin_acl_add_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['acl']['admin_acl_add']['d4os_io_radmin_admin_acl_add_users'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Users'),
    '#description'  => t("Users (firstname lastname;firstname lastname; firstname lastname...)"),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_add']['d4os_io_radmin_admin_acl_add_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_acl_add/js',
      'wrapper' => 'd4os-radmin-admin-acl-add-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_add']['d4os_io_radmin_admin_acl_add_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-acl-add-output">',
    '#suffix' => '</div>',
  );
// admin_acl_remove
  $form['d4os_io_radmin']['acl']['admin_acl_remove'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_acl_remove',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Remove a list of users from the access control list'),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_remove']['d4os_io_radmin_admin_acl_remove_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t("Region name."),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_remove']['d4os_io_radmin_admin_acl_remove_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['acl']['admin_acl_remove']['d4os_io_radmin_admin_acl_remove_users'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Users'),
    '#description'  => t("Users (firstname lastname;firstname lastname; firstname lastname...)"),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_remove']['d4os_io_radmin_admin_acl_remove_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_acl_remove/js',
      'wrapper' => 'd4os-radmin-admin-acl-remove-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_remove']['d4os_io_radmin_admin_acl_remove_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-acl-remove-output">',
    '#suffix' => '</div>',
  );
// admin_acl_list
  $form['d4os_io_radmin']['acl']['admin_acl_list'] = array(
    '#type'         => 'fieldset',
    '#title'        => 'admin_acl_list',
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
    '#description'  => t('Retrieve a list of users who can access the region'),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_list']['d4os_io_radmin_admin_acl_list_region_name'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region name'),
    '#description'  => t("Region name."),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_list']['d4os_io_radmin_admin_acl_list_region_uuid'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Region uuid'),
    '#description'  => t('Region uuid'),
    '#size'         => 36,
    '#maxlength'    => 36,
  );
  $form['d4os_io_radmin']['acl']['admin_acl_list']['d4os_io_radmin_admin_acl_list_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#ahah'   => array(
      'path'    => 'grid/radmin/admin_acl_list/js',
      'wrapper' => 'd4os-radmin-admin-acl-list-output',
      'method'  => 'replace',
      'effect'  => 'fade',
    ),
  );
  $form['d4os_io_radmin']['acl']['admin_acl_list']['d4os_io_radmin_admin_acl_list_output'] = array(
    '#title'  => t('Response'),
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-radmin-admin-acl-list-output">',
    '#suffix' => '</div>',
  );

}

function d4os_io_radmin_js($command) {
  // Prevent duplicate wrappers.
  unset($track_form['#prefix'], $track_form['#suffix']);
  //$field = 'd4os_oss_'. $service. '_'. $method;
  //$cmd = $_POST[$field];
  //if ($cmd == 'none' || $cmd == '') {
  //  $answer = theme('d4os_oss_wrongbutton');
  //}
  //else {
  //  $answer = theme('d4os_oss_answer', d4os_oss_service_call($service, $method, $cmd));
  //}
  $answer = '<pre>'. print_r(d4os_io_radmin_call($command, d4os_io_radmin_get_args($command)), true). '</pre>';
  $output = theme('status_messages') . $answer;

  $javascript = drupal_add_js(NULL, NULL);
  if (isset($javascript['setting'])) {
    $output .= '<script type="text/javascript">jQuery.extend(Drupal.settings, '. drupal_to_js(call_user_func_array('array_merge_recursive', $javascript['setting'])) .');</script>';
  }
  // Final rendering callback.
  drupal_json(array('status' => TRUE, 'data' => $output));
}

function d4os_io_radmin_get_args($command) {
  $args = array();
  switch ($command) {
// regions
    case 'admin_create_region':
      $args['region_id']              = $_POST['d4os_io_radmin_admin_create_region_region_id']; // str : optional
      $args['region_name']            = $_POST['d4os_io_radmin_admin_create_region_region_name']; // str
      $args['region_master_first']    = $_POST['d4os_io_radmin_admin_create_region_region_master_first']; // str
      $args['region_master_last']     = $_POST['d4os_io_radmin_admin_create_region_region_master_last']; // str
      $args['region_master_uuid']     = $_POST['d4os_io_radmin_admin_create_region_region_master_uuid'];
      $args['region_master_password'] = $_POST['d4os_io_radmin_admin_create_region_region_master_password']; // str
      $args['listen_ip']              = $_POST['d4os_io_radmin_admin_create_region_listen_ip']; // str
      $args['listen_port']            = $_POST['d4os_io_radmin_admin_create_region_listen_port']; // int
      $args['external_address']       = $_POST['d4os_io_radmin_admin_create_region_external_address']; // str
      $args['region_x']               = $_POST['d4os_io_radmin_admin_create_region_region_x']; // int
      $args['region_y']               = $_POST['d4os_io_radmin_admin_create_region_region_y']; // int
      $args['persist']                = $_POST['d4os_io_radmin_admin_create_region_persist']; // bool : optional
      $args['public']                 = $_POST['d4os_io_radmin_admin_create_region_public']; // bool : optional
      $args['enable_voice']           = $_POST['d4os_io_radmin_admin_create_enable_voice']; // bool : optional
      break;
    case 'admin_delete_region':
      $args['region_name'] = $_POST['d4os_io_radmin_admin_delete_region_region_name']; // str
      break;
    // TODO : add close region
    case 'admin_modify_region':
      $args['region_id']      = $_POST['d4os_io_radmin_admin_modify_region_region_id'];
      $args['region_name']    = $_POST['d4os_io_radmin_admin_modify_region_region_name'];
      $args['public']         = $_POST['d4os_io_radmin_admin_modify_region_public'];
      $args['enable_voice']   = $_POST['d4os_io_radmin_admin_modify_enable_voice'];
      break;
    case 'admin_region_query':
      $args['region_uuid'] = $_POST['d4os_io_radmin_admin_region_query_region_uuid'];
      $args['region_name'] = $_POST['d4os_io_radmin_admin_region_query_region_name'];
      break;
    case 'admin_shutdown':
      $delay = $_POST['d4os_io_radmin_admin_shutdown_delayed'];
      if (!empty($delay)) {
        $args['shutdown'] = 'delayed';
        $args['milliseconds'] = $delay*1000;
      }
      break;
    case 'admin_broadcast':
      $args['message'] = $_POST['d4os_io_radmin_admin_broadcast_message'];
      break;
    case 'admin_restart':
      $args['regionID'] = $_POST['d4os_io_radmin_admin_restart_regionID'];
      break;
    case 'admin_load_heightmap':
      $args['filename'] = $_POST['d4os_io_radmin_admin_load_heightmap_filename'];
      $args['regionid'] = $_POST['d4os_io_radmin_admin_load_heightmap_regionid'];
      break;
// users
    case 'admin_create_user':
      $args['user_firstname'] = $_POST['d4os_io_radmin_admin_create_user_user_firstname'];
      $args['user_lastname']  = $_POST['d4os_io_radmin_admin_create_user_user_lastname'];
      $args['user_password']  = $_POST['d4os_io_radmin_admin_create_user_user_password'];
      $args['start_region_x'] = $_POST['d4os_io_radmin_admin_create_user_start_region_x'];
      $args['start_region_y'] = $_POST['d4os_io_radmin_admin_create_user_start_region_y'];
      break;
    case 'admin_create_user_email':
      $args['user_firstname'] = $_POST['d4os_io_radmin_admin_create_user_email_user_firstname'];
      $args['user_lastname']  = $_POST['d4os_io_radmin_admin_create_user_email_user_lastname'];
      $args['user_password']  = $_POST['d4os_io_radmin_admin_create_user_email_user_password'];
      $args['start_region_x'] = $_POST['d4os_io_radmin_admin_create_user_email_start_region_x'];
      $args['start_region_y'] = $_POST['d4os_io_radmin_admin_create_user_email_start_region_y'];
      break;
    case 'admin_exists_user':
      $args['user_firstname'] = $_POST['d4os_io_radmin_admin_exists_user_user_firstname'];
      $args['user_lastname']  = $_POST['d4os_io_radmin_admin_exists_user_user_lastname'];
      break;
    case 'admin_update_user':
      $args['user_firstname'] = $_POST['d4os_io_radmin_admin_update_user_user_firstname'];
      $args['user_lastname']  = $_POST['d4os_io_radmin_admin_update_user_user_lastname'];
      $args['user_password']  = $_POST['d4os_io_radmin_admin_update_user_user_password'];
      $args['start_region_x'] = $_POST['d4os_io_radmin_admin_update_user_start_region_x'];
      $args['start_region_y'] = $_POST['d4os_io_radmin_admin_update_user_start_region_y'];
      break;
// region state
    case 'admin_load_xml':
      $args['filename']     = $_POST['d4os_io_radmin_admin_load_xml_filename'];
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_load_xml_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_load_xml_region_name'];
      $args['xml_version']  = $_POST['d4os_io_radmin_admin_load_xml_xml_version'];
      break;
    case 'admin_save_xml':
      $args['filename']     = $_POST['d4os_io_radmin_admin_save_xml_filename'];
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_save_xml_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_save_xml_region_name'];
      $args['xml_version']  = $_POST['d4os_io_radmin_admin_save_xml_xml_version'];
      break;
    case 'admin_load_oar':
      $args['filename']     = $_POST['d4os_io_radmin_admin_load_oar_filename'];
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_load_oar_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_load_oar_region_name'];
      break;
    case 'admin_save_oar':
      $args['filename']     = $_POST['d4os_io_radmin_admin_save_oar_filename'];
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_save_oar_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_save_oar_region_name'];
      break;
// acl
    case 'admin_acl_clear':
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_acl_clear_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_acl_clear_region_name']; // not working : failed to switch to region 00000000-0000-0000-0000-000000000000
      break;
    case 'admin_acl_add': // not working : Cannot cast from source type to destination type.
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_acl_add_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_acl_add_region_name']; // not working : failed to switch to region 00000000-0000-0000-0000-000000000000
      $args['users']        = explode(';', $_POST['d4os_io_radmin_admin_acl_add_users']);
      break;
    case 'admin_acl_remove': // not working : Cannot cast from source type to destination type.
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_acl_remove_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_acl_remove_region_name']; // not working : failed to switch to region 00000000-0000-0000-0000-000000000000
      $args['users']        = explode(';', $_POST['d4os_io_radmin_admin_acl_remove_users']);
      break;
    case 'admin_acl_list': // not working : return empty array (users)
      $args['region_uuid']  = $_POST['d4os_io_radmin_admin_acl_list_region_uuid'];
      $args['region_name']  = $_POST['d4os_io_radmin_admin_acl_list_region_name']; // not working : failed to switch to region 00000000-0000-0000-0000-000000000000
      break;
  }
  return $args;
}

function d4os_io_radmin_call($command, $args) {
  global $grid_url;
  $args['password'] = variable_get('d4os_io_radmin_default_password', 'mypw');
  $data = array();
  if (module_exists('d4os_oss') && variable_get('d4os_io_radmin_use_oss', 1)) {
    $uuid = variable_get('d4os_oss_default_opensim_uuid', 'e978e986-61a9-4d93-a40a-c5e9e05047d0');
    $data['result'] = xmlrpc(d4os_oss_build_url(), 'radmin_proxy', $uuid, $command, $args);
  }
  else {
    $data['result'] = xmlrpc($grid_url, $command, $args);
  }
  $data['error'] = xmlrpc_error_msg();
  $data['errno'] = xmlrpc_errno();
  return $data;
}
