<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

function d4os_ui_stats_levels_widgets_bars_d4os_widget_add() {
  $widget = array(
    'name'  => 'bars',
    'title' => t('Bars'),
  );
  return $widget;
}

function d4os_ui_stats_levels_widgets_bars_params_form() {
  
}
function d4os_ui_stats_levels_widgets_bars_params_save($edit) {
  
}

function d4os_ui_stats_levels_widgets_bars_display($data) {
  $js = '
  SimFPS = '. round($data->SimFPS).'
  PhyFPS = '. round($data->PhyFPS).'
  Memory = '. round($data->Memory);
  drupal_add_js($js, 'inline', 'footer');
  drupal_add_js(libraries_get_path('jquery.easing').'/jquery.easing.js');
  drupal_add_css(drupal_get_path('module', 'd4os_ui_stats_levels_widgets_bars').'/css/d4os_ui_stats_levels_widgets_bars.css');
  drupal_add_js(drupal_get_path('module', 'd4os_ui_stats_levels_widgets_bars').'/js/d4os_ui_stats_levels_widgets_bars.js', 'module', 'footer');
  $output = theme('d4os_ui_stats_levels_widgets');
  return $output;
}