<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

// TODO : see what we can do with : http://domain.com:9000/SStats/

function d4os_ui_stats_grid_stats_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();
  switch ($op) {

    case 'list':
      $block['grid_stats']["info"] = t('Grid stats');
      break;

    case 'view':
      switch ($delta) {
        case 'grid_stats':
          $content = d4os_ui_stats_grid_stats_display();
          $block['subject'] = t('Grid stats');
          $block['content'] = $content;
          break;
      }
      break;
  }
  return $block;
}

function d4os_ui_stats_grid_stats_display($load_js=TRUE) {
  global $grid_url, $base_url;
  // get the grid status
  $online = d4os_grid_is_online();
  // add the login uri
  $loginuri = variable_get('d4os_default_login_uri', $base_url). ':'. variable_get('d4os_default_login_port', '8002');
  // build the output
  $output = theme('d4os_ui_stats_status', $online, $loginuri);
  if (variable_get('d4os_ui_stats_status_use_timer', 1)) {
    if ($load_js) {
      drupal_add_js(libraries_get_path('jquery.timer').'/jquery.timer.js');
      $js_vars = array(
        'timer'  => variable_get('d4os_ui_stats_status_timer', 15),
      );
      drupal_add_js(array('d4os_ui_stats_status' => $js_vars), 'setting');
      drupal_add_js(drupal_get_path('module', 'd4os_ui_stats_status').'/js/d4os_ui_stats_status.js', 'module', 'footer');
    }
  }
  return $output;
}

function d4os_ui_stats_grid_stats_theme() {
  return array(
    // status
    'd4os_ui_stats_grid_stats' => array(
      'arguments' => array('stats' => array()),
    ),
  );
}

function theme_d4os_ui_stats_grid_stats($online, $loginuri) {
  // TODO : see the loginuri with counter
  $output = '';//'<div><dl><dt>'. t('Login uri'). '</dt><dd>'. $loginuri. '</dd></dl></div>';
  if ($online) {
    $output .= '<div id="grid_status" class="messages status">'. t('Online'). '</div>';
  }
  else {
    $output .= '<div id="grid_status" class="messages error">'. t('Offline'). '</div>';
  }
  return $output;
}