<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

// TODO : see what we can do with : http://domain.com:9000/SStats/

function d4os_ui_stats_grid_stats_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();
  switch ($op) {

    case 'list':
      $block['grid_stats']["info"] = t('Grid stats');
      break;

    case 'view':
      switch ($delta) {
        case 'grid_stats':
          $values = module_invoke_all('os_grid_get_stats');
          $content = theme('d4os_ui_stats_grid_stats', $values['data']);
          $block['subject'] = t('Grid stats');
          $block['content'] = $content;
          break;
      }
      break;
  }
  return $block;
}

function d4os_ui_stats_grid_stats_theme() {
  return array(
    // status
    'd4os_ui_stats_grid_stats' => array(
      'arguments' => array('values' => array()),
    ),
  );
}

function theme_d4os_ui_stats_grid_stats($values) {
  $output = '<div id="grid-stats">';
  $output .= '<ul>';
  $output .= '<li>'. t('Now online'). ' : '. $values->now_online. '</li>';
  $output .= '<li>'. t('Last month online'). ' : '. $values->last_month_online. '</li>';
  $output .= '<li>'. t('Users count'). ' : '. $values->users_count. '</li>';
  $output .= '<li>'. t('Regions count'). ' : '. $values->regions_count. '</li>';
  $output .= '</ul>';
  $output .= '</div>';
  return $output;
}