<?php
/**
 * @package    d4os_io_simian
 * @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

global $base_url, $simian_url;
$simian_url = variable_get('d4os_io_simian_url', variable_get('d4os_default_grid_uri', $base_url). '/Grid/');

function d4os_io_simian_menu() {
  $items = array();
  $items['admin/settings/d4os/io/simian'] = array(
    'title'             => 'simian',
    'description'       => 'd4os io simian settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_simian_admin'),
    'access arguments'  => array('admin d4os simian'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os_io_simian.admin.inc'
   );
  /*$items['grid/simian/test'] = array(
    'title'             => 'simian',
    'description'       => 'd4os simian',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_simian_test_form'),
    'access arguments'  => array('access d4os simian test'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'd4os_io_simian.test.inc'
   );
  // ahah
  $items['grid/simian/test/%/js'] = array(
    'page callback'     => 'd4os_io_simian_test_js',
    'page arguments'    => array(2),
    'access arguments'  => array('access d4os simian test'),
    'type '             => MENU_CALLBACK,
  );*/
  return $items;
}

function d4os_io_simian_perm() {
  return array(
    'admin d4os simian',
    'access d4os simian test'
  );
}

function d4os_io_simian_load_includes() {
  module_load_include('inc', 'd4os_io_simian', 'd4os_io_simian_user');
}

d4os_io_simian_load_includes();
