<?php
/**
 * @package    d4os_io_profiles
 * @copyright Copyright (C) 2010-2012 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @link      http://www.d4os.org
 * @license   GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

/**
 * Implementation of hook help
 */
function d4os_io_profiles_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os_io_profiles':
      return '<p>' . t('OpenSim grid profiles management') . '</p>';
  }
}

function d4os_io_profiles_menu() {

  $items['admin/settings/d4os/io/profiles/registration'] = array(
    'title'             => 'Profiles registration',
    'description'       => 'd4os ui profiles registration settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_profiles_admin'),
    'access arguments'  => array('admin d4os ui profiles'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os_io_profiles.admin.inc'
   );
  return $items;
}

function d4os_io_profiles_perm() {
  return array(
    'admin d4os ui profiles',
  );
}

function d4os_io_profiles_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'delete') {
    d4os_io_profiles_delete_user($account->uid);
  }
}

function d4os_io_profiles_delete_user($uid) {
  // get the user uuid
  $uuid = db_result(db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=%d", $uid));
  if ($uuid === FALSE) {
    return;
  }
  $d4os_profiles = D4OS_IO::create('Profiles');
  $d4os_profiles->delete_profile($uuid);
}

function d4os_io_profiles_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'd4os_ui_users_grid_registration_form') {
    if (variable_get('d4os_io_profiles_create_profile_on_register', 1)) {
      $form['#submit'][] = 'd4os_io_profiles_grid_registration_fom_submit';
    }
  }
}

function d4os_io_profiles_grid_registration_fom_submit($form, &$form_state) {
  // check if the user is registered
  $uuid = db_result(db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=%d", arg(1)));
  // assign the role
  if ($uuid !== FALSE) {
    $d4os_profiles = D4OS_IO::create('Profiles');
    $d4os_profiles->save_profile(
      d4os_io_profiles_create_profile($uuid)
    );
  }
}

function d4os_io_profiles_create_profile($uuid) {
  $profile = new stdClass();
  $profile->useruuid = $uuid;
  $profile->profileSkillsMask = 0;
  $profile->profileWantToMask = 0;
  $profile->profileAboutText = variable_get('d4os_io_profiles_default_profile_about_text', 'I am a new user');
  $profile->profileFirstText = variable_get('d4os_io_profiles_default_profile_first_text', 'I am as real as you are');
  $profile->profileImage = variable_get('d4os_io_profiles_default_profile_image',UUID_ZERO);
  $profile->profileFirstImage = variable_get('d4os_io_profiles_default_profile_first_image',UUID_ZERO);
  $profile->profileURL = '';
  $profile->profilePartner = '';
  return $profile;
}