<?php
/**
 * @package   d4os_ui_friends
 * @copyright Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license   GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

/**
 * Implementation of hook_block().
 */
function d4os_ui_friends_block($op = 'list', $delta = '', $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['online_friends'] = array(
        'info'       => t('Friends'),
        'status'     => TRUE,
        'weight'     => 0,
        'visibility' => 1,
        'pages'      => 'user/*',
      );

      $blocks['offline_friends'] = array(
        'info'       => t('Friends'),
        'status'     => TRUE,
        'weight'     => 0,
        'visibility' => 1,
        'pages'      => 'user/*',
      );
      return $blocks;

    case 'view':
      switch ($delta) {
        case 'online_friends':
          $block['subject'] = t('Title of configurable-text block');
          $block['content'] = d4os_ui_friends_show_online_friends();
          break;
        case 'offline_friends':
          $block['subject'] = t('Title of block #2');
          $block['content'] = d4os_ui_friends_show_offline_friends();
          break;
      }
      return $block;
  }
  return $block;
}

/**
 * A block content function.
 */
function d4os_ui_friends_show_online_friends() {
  return '';
}

/**
 * A block content function.
 */
function d4os_ui_friends_show_offline_friends() {
  return '';
}

function d4os_ui_friends_list_params_save($edit) {
  variable_set('d4os_ui_friends_list_quantity',       $edit['d4os_ui_friends_list_quantity']);
}

function d4os_ui_friends_online_params_save($edit) {
  variable_set('d4os_ui_friends_online_quantity',   $edit['d4os_ui_friends_online_quantity']);
}

function d4os_ui_friends_display_friends() {
  // get the friends list
  $friends = module_invoke_all('os_friends_get_friends', $GLOBALS['user']->d4os['grid']['account']['uuid']);
  // build the output
  if ($friends['success'] && count($friends['data'])) {
    $output = theme('d4os_ui_friends_display_friends', $friends['data']);
  }
  else {
    $output = t('No friends');
  }
  return $output;
}

function d4os_ui_friends_display_online_friends() {
  // get the friends list
  $online_friends = module_invoke_all('os_friends_get_online_friends', $GLOBALS['user']->d4os['grid']['account']['uuid']);
  // build the output
  if ($online_friends['success'] && count($online_friends['data'])) {
    $output = theme('d4os_ui_friends_display_online_friends', $online_friends['data']);
  }
  else {
    $output = t('No friends online.');
  }
  return $output;
}

function d4os_ui_friends_theme() {
  return array(
    'd4os_ui_friends_display_friends' => array(
      'arguments' => array('friends' => array()),
    ),
    'd4os_ui_friends_display_online_friends' => array(
      'arguments' => array('friends' => array()),
    ),
  );
}

function theme_d4os_ui_friends_display_friends($friends) {
  $output = '<div id="friends-list">';
  $output .= '<ul>';
  foreach ($friends as $friend) {
    $output .= '<li>'. $friend->name. '</li>';
  }
  $output .= '</ul>';
  $output .= '</div>';
  return $output;
}

function theme_d4os_ui_friends_display_online_friends($friends) {
  $output = '<div id="online-friends-list">';
  $output .= '<ul>';
  foreach ($friends as $friend) {
    $output .= '<li>'. $friend->name. '</li>';
  }
  $output .= '</ul>';
  $output .= '</div>';
  return $output;
}
