<?php

/**
 *  Implements hook_menu().
 */
function d4os_ui_friends_menu() {
  $items = array();
  $items['user/%user/grid/friends'] = array(
    'title' => 'Friends',
    'description' => 'See own friends list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d4os_ui_friends_list_form', 1),
    'access callback' => 'd4os_ui_friends_can_see_friends',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/%user/grid/friends/%/details'] = array(
    'title' => 'Friend details',
    'description' => 'Change friend details.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d4os_ui_friends_friend_details_form', 1, 4),
    'access callback' => 'd4os_ui_friends_can_see_friends',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['user/%user/grid/friends/%/delete'] = array(
    'title' => 'Friend details',
    'description' => 'Change friend details.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d4os_ui_friends_friend_delete_form', 1, 4),
    'access callback' => 'd4os_ui_friends_can_see_friends',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function d4os_ui_friends_can_see_friends($account) {
  // check if the user has an account on the grid
  $uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=:uid", array(':uid' => $account->uid))->fetchField();
  if ($uuid === FALSE || is_null($uuid)) {
    return FALSE;
  }
  // check if the user is the owner of the account or is admin
  if ($GLOBALS['user']->uid == $account->uid || $GLOBALS['user']->uid == 1 || isset($GLOBALS['user']->roles[variable_get('user_admin_role', 0)])) {
    return TRUE;
  }
  return FALSE;
}

function d4os_ui_friends_list_form($form, &$form_state, $account) {
  $form = array();
  // get the account uuid
  $uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=:uid", array(':uid' => $account->uid))->fetchField();
  if ($uuid === FALSE || is_null($uuid)) {
    drupal_set_message(t('User not registered on the grid.'), 'error');
    return $form;
  }
  // check if friends are available
  $d4os_friends = D4OS_IO::create('Friends');
  $d4os_friends->ping();
  if ($d4os_friends->response->success !== TRUE) {
    drupal_set_message(t('You can not see the friends list.'), 'error');
    drupal_set_message(t('Please try again later.'), 'error');
    return $form;
  }
  // get the friends
  $friends = $d4os_friends->get_friends($uuid);
  $friends_qty = count($friends);
  if (!$friends_qty) {
    drupal_set_message(t('No friends found.'), 'error');
    return $form;
  }
  // build output
  $id = 0;
  $local_qty = 0;
  $hg_qty = 0;
  $unknown_qty = 0;
  $local_table = d4os_ui_friends_get_list_table_params(t('Local'));
  $hypergrid_table = d4os_ui_friends_get_list_table_params(t('Hypergrid'), TRUE);
  $unknown_table = d4os_ui_friends_get_list_table_params(t('Unknown'));
  foreach ($friends as $friend) {
    if (!is_null($friend->name)) {
      $values = array(
        'uid' => $account->uid,
        'id' => $id,
        'flags' => $friend->Flags,
        'name' => $friend->name,
        'friend' => $friend->Friend
      );
      $local_table['rows'][] = d4os_ui_friends_get_list_row($values);
      $local_qty++;
    }
    else {
      // check if this is a hypergrid friend
      $hg_uuid = NULL;
      $hg_uri = NULL;
      $hg_name = NULL;
      $values = explode(';', $friend->Friend);
      if (isset($values[0])) {
        $hg_uuid = $values[0];
      }
      if (isset($values[1])) {
        $hg_uri = $values[1];
      }
      if (isset($values[2])) {
        $hg_name = $values[2];
      }
      if (!is_null($hg_name)) {
        $values = array(
          'uid' => $account->uid,
          'id' => $id,
          'flags' => $friend->Flags,
          'name' => $hg_name,
          'friend' => $friend->Friend,
          'hg_uri' => $hg_uri
        );
        $hypergrid_table['rows'][] = d4os_ui_friends_get_list_row($values, TRUE);
        $hg_qty++;
      }
      else {
        $values = array(
          'uid' => $account->uid,
          'id' => $id,
          'flags' => $friend->Flags,
          'name' => $friend->Friend,
          'friend' => $friend->Friend,
        );
        $unknown_table['rows'][] = d4os_ui_friends_get_list_row($values);
        $unknown_qty++;
      }
    }
    $id++;
  }
  $form = array();
  if ($local_qty) {
    $form['local'] = array(
      '#type' => 'fieldset',
      '#title' => t('Local'). ' ('. $local_qty. ')',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE
    );
    $form['local']['table'] = array(
      '#markup' => theme_table($local_table)
    );
  }
  if ($hg_qty) {
    $form['hg'] = array(
      '#type' => 'fieldset',
      '#title' => t('Hypergrid'). ' ('. $hg_qty. ')',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE
    );
    $form['hg']['table'] = array(
      '#markup' => theme_table($hypergrid_table)
    );
  }
  if ($unknown_qty) {
    $form['hg'] = array(
      '#type' => 'fieldset',
      '#title' => t('Unknown'). ' ('. $unknown_qty. ')',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE
    );
    $form['hg']['table'] = array(
      '#markup' => theme_table($unknown_table)
    );
  }
  return $form;
}

function d4os_ui_friends_get_list_table_params($caption, $hg = FALSE) {
  $params = array();
  $params['sticky'] = TRUE;
  $params['attributes'] = array('sticky' => TRUE);
  $params['caption'] = $caption;
  $params['colgroups'] = array();
  $params['empty'] = '';
  $params['header'] = array();
  $params['header']['name'] = array('data' => t('Name'));
  if ($hg) {
    $params['header']['hguri'] = array('data' => t('See online'));
  }
  $params['header']['see_online'] = array('data' => t('See online'));
  $params['header']['see_on_map'] = array('data' => t('See on map'));
  $params['header']['allow_modif'] = array('data' => t('Allow modify objects'));
  $params['header']['edit'] = array('data' => t('Edit'));
  $params['header']['delete'] = array('data' => t('Delete'));
  return $params;
}

function d4os_ui_friends_get_list_row($values, $hg = FALSE) {
  $flags = d4os_ui_friends_get_flags($values['flags']);
  $row = array();
  $row[] = $values['name'];
  if ($hg) {
    $row[] = $values['hg_uri'];
  }
  $row[] = '<span class="'. (($flags['see_online']) ? 'yes">'.t('Yes'): 'no">'.t('No')). '</span>';
  $row[] = '<span class="'. (($flags['see_on_map']) ? 'yes">'.t('Yes'): 'no">'.t('No')). '</span>';
  $row[] = '<span class="'. (($flags['modify_objects']) ? 'yes">'.t('Yes'): 'no">'.t('No')). '</span>';
  $row[] = l(t('Edit details'), 'user/'. $values['uid']. '/grid/friends/'. urlencode($values['friend']). '/details');
  $row[] = l(t('Delete'), 'user/'. $values['uid']. '/grid/friends/'. urlencode($values['friend']). '/delete');
  return $row;
}

function d4os_ui_friends_friend_delete_form($form, &$form_state, $account, $friend) {
  $form = array(
    'uid' => array(
      '#type' => 'value',
      '#value' => $account->uid
    ),
    'friend' => array(
      '#type' => 'value',
      '#value' => urldecode($friend)
    ),
    'displayed' => array(
      '#type' => 'item',
      '#title' => urldecode($friend)
    )
  );
  return confirm_form(
    $form,
    t('Are you sure you want to delete this friend ?'),
    'user/'.$account->uid.'/grid/friends'
  );
}

function d4os_ui_friends_friend_delete_form_submit($form, &$form_state) {
  // get the account uuid
  $uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=:uid", array(':uid' => $form_state['values']['uid']))->fetchField();
  if ($uuid === FALSE || is_null($uuid)) {
    drupal_set_message(t('User not registered on the grid.'));
    return;
  }
  $d4os_friends = D4OS_IO::create('Friends');
  $d4os_friends->delete_friend($uuid, $form_state['values']['friend']);
  drupal_set_message(t('Friend %friend was removed.', array('%friend' => $form_state['values']['friend'])));
  $form_state['redirect'] = 'user/'.$form_state['values']['uid'].'/grid/friends';
}

function d4os_ui_friends_friend_details_form($form, &$form_state, $account, $friend_uuid) {
  $form = array();
  // get the account uuid
  $uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=:uid", array(':uid' => $account->uid))->fetchField();
  if ($uuid === FALSE || is_null($uuid)) {
    drupal_set_message(t('User not registered on the grid.'));
    return $form;
  }
  // check if friends are available
  $d4os_friends = D4OS_IO::create('Friends');
  $d4os_friends->ping();
  if ($d4os_friends->response->success !== TRUE) {
    drupal_set_message(t('You can not see the friend details.'), 'error');
    drupal_set_message(t('Please try again later.'), 'error');
    return $form;
  }
  // get the friend details
  $friend = $d4os_friends->get_friend($uuid, urldecode($friend_uuid));
  if (is_null($friend)) {
    drupal_set_message(t('Friend not found.'));
    drupal_goto('user/'. $account->uid. '/grid/friends');
    return;
  }
  $flags = d4os_ui_friends_get_flags($friend->Flags);
  $form[$friend_uuid] = array(
    '#type' => 'fieldset',
    '#title' => $friend->name,
    '#collapsible' => FALSE,
    '#collapsed' => TRUE
  );
  $form[$friend_uuid]['see_online'] = array(
    '#type' => 'checkbox',
    '#title' => t('See online'),
    '#default_value' => $flags['see_online']
  );
  $form[$friend_uuid]['see_on_map'] = array(
    '#type' => 'checkbox',
    '#title' => t('See on map'),
    '#default_value' => $flags['see_on_map']
  );
  $form[$friend_uuid]['modify_objects'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow modify objects'),
    '#default_value' => $flags['modify_objects']
  );
  $form['avatar_uuid'] = array(
    '#type' => 'hidden',
    '#value' => $uuid
  );
  $form['friend_uuid'] = array(
    '#type' => 'hidden',
    '#value' => $friend->Friend
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Modify'),
  );
  drupal_set_title($friend->name);
  return $form;
}

function d4os_ui_friends_friend_details_form_submit($form, &$form_state) {
  $flags = 0;
  if ($form_state['values']['see_online']) {
    $flags += 1;
  }
  if ($form_state['values']['see_on_map']) {
    $flags += 2;
  }
  if ($form_state['values']['modify_objects']) {
    $flags += 4;
  }
  $d4os_friends = D4OS_IO::create('Friends');
  $updated = $d4os_friends->set_flags($form_state['values']['avatar_uuid'], $form_state['values']['friend_uuid'], $flags);
}

function d4os_ui_friends_get_flags($flags) {
  $values = array(
    'see_online' => FALSE,
    'see_on_map' => FALSE,
    'modify_objects' => FALSE
  );
  switch ($flags) {
    case 1:
      $values['see_online'] = TRUE;
      break;
    case 2:
      $values['see_on_map'] = TRUE;
      break;
    case 3:
      $values['see_online'] = TRUE;
      $values['see_on_map'] = TRUE;
      break;
    case 4:
      $values['modify_objects'] = TRUE;
      break;
    case 5:
      $values['see_online'] = TRUE;
      $values['modify_objects'] = TRUE;
      break;
    case 6:
      $values['see_on_map'] = TRUE;
      $values['modify_objects'] = TRUE;
      break;
    case 7:
      $values['see_online'] = TRUE;
      $values['see_on_map'] = TRUE;
      $values['modify_objects'] = TRUE;
      break;
  }
  return $values;
}

/**
 * Implements hook_block_info().
 */
function d4os_ui_friends_block_info() {
  $blocks = array();
  $blocks['d4os_ui_friends_online_friends'] = array(
    'info' => t('Online friends')
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function d4os_ui_friends_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'd4os_ui_friends_online_friends':
      $block['subject'] = t('Online friends');
      $block['content'] = d4os_ui_friends_block_content($delta);
      break;
  }
  return $block;
}

function d4os_ui_friends_block_content($delta) {
  // get the account uuid
  $uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid=:uid", array(':uid' => $GLOBALS['user']->uid))->fetchField();
  if ($uuid === FALSE || is_null($uuid)) {
    return '';
  }
  // check if friends are available
  $d4os_friends = D4OS_IO::create('Friends');
  $d4os_friends->ping();
  if ($d4os_friends->response->success !== TRUE) {
    return '';
  }
  // get the friends
  $friends = $d4os_friends->get_online_friends($uuid);
  $friends_qty = count($friends);
  if (!$friends_qty) {
    return t('No friends online');
  }
  $uids = d4os_ui_users_get_uid_by_uuid(array_keys($friends));
  // build the output
  $output = '<ul class="friends-list">';
  foreach ($friends as $friend) {
    if(isset($uids[$friend->PrincipalID])) {
      $output .= '<li>'. l($friend->name, 'user/'. $uids[$friend->PrincipalID]). '</li>';
    }
    else {
      $output .= '<li>'. $friend->name. '</li>';
    }
  }
  $output .= '</ul>';
  return $output;
}
