<?php
/**
 * @package    d4os_io_osservices
 * @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * D4os is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

function d4os_io_osservices_help($path, $arg) {
  switch ($path) {
    case 'admin/help#d4os_io_osservices':
      return '<p>' . t('OpenSim grid management') . '</p>';
  }
}

function d4os_io_osservices_menu() {
  $items = array();
  $items['admin/settings/d4os/io/osservices'] = array(
    'title'             => 'osservices',
    'description'       => 'd4os io osservices settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_osservices_admin'),
    'access arguments'  => array('admin d4os osservices'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'd4os_io_osservices.admin.inc'
  );
  $items['grid/osservices'] = array(
    'title'             => 'osservices',
    'description'       => 'd4os osservices',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('d4os_io_osservices_form'),
    'access arguments'  => array('access d4os osservices'),
    'type'              => MENU_NORMAL_ITEM,
  );
  // ahah
  $items['grid/osservices/%/%/js'] = array(
    'page callback'     => 'd4os_io_osservices_js',
    'page arguments'    => array(2, 3),
    'access arguments'  => array('access d4os osservices'),
    'type '             => MENU_CALLBACK,
  );
  return $items;
}

function d4os_io_osservices_perm() {
  return array(
    'admin d4os osservices',
    'access d4os osservices'
  );
}

function d4os_io_osservices_form($form) {
  $actions = array(
    'none'  => t('No action'),
    'start' => t('Start'),
    'stop'  => t('Stop'),
    'kill'  => t('Kill'),
  );
  $form = array();

// grid
  $form['d4os_io_osservices_grid'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Grid'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_grid']['d4os_io_osservices_grid_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('Grid control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_grid']['d4os_io_osservices_grid_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_grid_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/grid/control_service/js',
      'wrapper'   => 'd4os-oss-grid-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_grid']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_grid']['response']['d4os_io_osservices_grid_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-grid-output">',
    '#suffix' => '</div>',
  );

// maps
  $form['d4os_io_osservices_osmaps'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('OsMaps'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_osmaps']['d4os_io_osservices_osmaps_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('OsMaps control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_osmaps']['d4os_io_osservices_osmaps_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_osmaps_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/osmaps/control_service/js',
      'wrapper'   => 'd4os-oss-osmaps-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_osmaps']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_osmaps']['response']['d4os_io_osservices_osmaps_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-osmaps-output">',
    '#suffix' => '</div>',
  );

// users
  $form['d4os_io_osservices_users'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Users'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_users']['d4os_io_osservices_users_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('Users control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_users']['d4os_io_osservices_users_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_users_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/users/control_service/js',
      'wrapper'   => 'd4os-oss-users-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_users']['d4os_io_osservices_users_console_proxy'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Console commands'),
    '#description'  => t("Console commands."),
  );
  $form['d4os_io_osservices_users']['d4os_io_osservices_users_console_proxy_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_users_console_proxy_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/users/console_proxy/js',
      'wrapper'   => 'd4os-oss-users-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_users']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_users']['response']['d4os_io_osservices_users_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-users-output">',
    '#suffix' => '</div>',
  );

// robust
  $form['d4os_io_osservices_robust'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Robust'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_robust']['d4os_io_osservices_robust_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('Robust control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_robust']['d4os_io_osservices_robust_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_robust_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/robust/control_service/js',
      'wrapper'   => 'd4os-oss-robust-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_robust']['d4os_io_osservices_robust_console_proxy'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Console commands'),
    '#description'  => t("Console commands."),
  );
  $form['d4os_io_osservices_robust']['d4os_io_osservices_robust_console_proxy_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_robust_console_proxy_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/robust/console_proxy/js',
      'wrapper'   => 'd4os-oss-robust-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_robust']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_robust']['response']['d4os_io_osservices_robust_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-robust-output">',
    '#suffix' => '</div>',
  );

// messaging
  $form['d4os_io_osservices_messaging'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Messaging'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_messaging']['d4os_io_osservices_messaging_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('Messaging control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_messaging']['d4os_io_osservices_messaging_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_messaging_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/messaging/control_service/js',
      'wrapper'   => 'd4os-oss-messaging-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_messaging']['d4os_io_osservices_messaging_console_proxy'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Console commands'),
    '#description'  => t("Console commands."),
  );
  $form['d4os_io_osservices_messaging']['d4os_io_osservices_messaging_console_proxy_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_messaging_console_proxy_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/messaging/console_proxy/js',
      'wrapper'   => 'd4os-oss-messaging-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_messaging']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_messaging']['response']['d4os_io_osservices_messaging_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-messaging-output">',
    '#suffix' => '</div>',
  );

// opensim
  $form['d4os_io_osservices_opensim'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('OpenSim'),
    '#collapsible'  => TRUE,
    '#collapsed'    => TRUE,
  );
  $form['d4os_io_osservices_opensim']['d4os_io_osservices_opensim_control_service'] = array(
    '#type'         => 'select',
    '#title'        => t('OpenSim control service'),
    '#options'      => $actions,
    '#description'  => t('Start stop kill.'),
  );
  $form['d4os_io_osservices_opensim']['d4os_io_osservices_opensim_control_service_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_opensim_control_service_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/opensim/control_service/js',
      'wrapper'   => 'd4os-oss-opensim-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_opensim']['d4os_io_osservices_opensim_console_proxy'] = array(
    '#type'         => 'textfield',
    '#title'        => t('Console commands'),
    '#description'  => t("Console commands."),
  );
  $form['d4os_io_osservices_opensim']['d4os_io_osservices_opensim_console_proxy_submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Go'),
    '#submit' => array('d4os_io_osservices_opensim_console_proxy_submit'),
    '#ahah'   => array(
      'path'      => 'grid/oss/opensim/console_proxy/js',
      'wrapper'   => 'd4os-oss-opensim-output',
      'method'    => 'replace',
      'effect'    => 'fade',
      'progress'  => array('type' => 'throbber', 'message' => t('Connecting...'))
    ),
  );
  $form['d4os_io_osservices_opensim']['response'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Response'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_io_osservices_opensim']['response']['d4os_io_osservices_opensim_output'] = array(
    '#type'   => 'item',
    '#prefix' => '<div id="d4os-oss-opensim-output">',
    '#suffix' => '</div>',
  );

  return $form;
}


function d4os_io_osservices_js($service, $method) {
  // Prevent duplicate wrappers.
  unset($track_form['#prefix'], $track_form['#suffix']);
  $field = 'd4os_io_osservices_'. $service. '_'. $method;
  $cmd = $_POST[$field];
  if ($cmd == 'none' || $cmd == '') {
    $answer = theme('d4os_io_osservices_wrongbutton');
  }
  else {
    $answer = theme('d4os_io_osservices_answer', d4os_io_osservices_service_call($service, $method, $cmd));
  }
  $output = theme('status_messages') . $answer;

  $javascript = drupal_add_js(NULL, NULL);
  if (isset($javascript['setting'])) {
    $output .= '<script type="text/javascript">jQuery.extend(Drupal.settings, '. drupal_to_js(call_user_func_array('array_merge_recursive', $javascript['setting'])) .');</script>';
  }
  // Final rendering callback.
  drupal_json(array('status' => TRUE, 'data' => $output));
}

function d4os_io_osservices_service_call($service, $method, $command) {
  $uuids = array();
  $services = array();
  switch ($service) {
    case 'grid':
      $services[] = 'users';
      $uuids[] = variable_get('d4os_io_osservices_default_users_uuid', 'c70a2070-e028-11de-b2b0-0015f297a987');
      $services[] = 'robust';
      $uuids[] = variable_get('d4os_io_osservices_default_robust_uuid', 'a513750a-e02a-11de-b2b0-0015f297a987');
      $services[] = 'messaging';
      $uuids[] = variable_get('d4os_io_osservices_default_messaging_uuid', 'b4e36656-e02b-11de-b2b0-0015f297a987');
      $services[] = 'opensim';
      $uuids[] = variable_get('d4os_io_osservices_default_opensim_uuid', 'e978e986-61a9-4d93-a40a-c5e9e05047d0');
      break;
    case 'osmaps':
      $services[] = 'osmaps';
      $uuids[] = variable_get('d4os_io_osservices_default_osmaps_uuid', 'a9468cec-e02b-11de-b2b0-0015f297a987');
      break;
    case 'users':
      $services[] = 'users';
      $uuids[] = variable_get('d4os_io_osservices_default_users_uuid', 'c70a2070-e028-11de-b2b0-0015f297a987');
      break;
    case 'robust':
      $services[] = 'robust';
      $uuids[] = variable_get('d4os_io_osservices_default_robust_uuid', 'a513750a-e02a-11de-b2b0-0015f297a987');
      break;
    case 'messaging':
      $services[] = 'messaging';
      $uuids[] = variable_get('d4os_io_osservices_default_messaging_uuid', 'b4e36656-e02b-11de-b2b0-0015f297a987');
      break;
    case 'opensim':
      $services[] = 'opensim';
      $uuids[] = variable_get('d4os_io_osservices_default_opensim_uuid', 'e978e986-61a9-4d93-a40a-c5e9e05047d0');
      break;
  }
  $answers = array();
  foreach ($uuids as $k => $uuid) {
    $data = array(
      'service' => $services[$k],
      'uuid'    => $uuid,
      'method'  => $method,
      'command' => $command
    );
    $data['result'] = xmlrpc(d4os_io_osservices_build_url(), $method, $uuid, $command);
    $data['error'] = xmlrpc_error_msg();
    $data['errno'] = xmlrpc_errno();
    $answers[] = $data;
    //sleep(variable_get('d4os_io_osservices_default_grid_pause', 5));
  }
  return $answers;
}

function d4os_io_osservices_build_url() {
  $url = 'https://';
  $url .= variable_get('d4os_io_osservices_default_user', 'admin');
  $url .= ':';
  $url .= variable_get('d4os_io_osservices_default_pass', 'f6fdffe48c908deb0f4c3bd36c032e72');
  $url .= '@';
  $url .= variable_get('d4os_io_osservices_default_uri', '127.0.0.1');
  $url .= ':';
  $url .= variable_get('d4os_io_osservices_default_port', '7999');
  $url .= '/RPC2';
  return $url;
}

function d4os_io_osservices_theme(){
  return array(
    'd4os_io_osservices_answer' => array(
      'arguments' => array('answers' => array()),
    ),
    'd4os_io_osservices_wrongbutton' => array(),
  );
}

function theme_d4os_io_osservices_answer($answers) {
  $output = '';
  foreach ($answers as $answer) {
    $status = $answer['error'] ? 'error' : 'status';
    $status = $answer['result'] == 'noproc' || $answer['result'] == 'existing' ? 'warning' : $status;
    $result = $answer['result'];
    if (is_array($result)) {
      $result = '
<ul>
  <li><b>'. t('Success'). '</b> : '. $result['success']. '</li>
  <li><b>'. t('StdOut'). '</b> : '. $result['stdout']. '</li>
</ul>
      ';
    }
    $output .= '
<div class="messages '. $status. '">
  <ul>
    <li><b>'. t('Service'). '</b> : '. $answer['service']. '</li>
    <li><b>'. t('UUID'). '</b> : '. $answer['uuid']. '</li>
    <li><b>'. t('Method'). '</b> : '. $answer['method']. '</li>
    <li><b>'. t('Command'). '</b> : '. $answer['command']. '</li>
    <li><b>'. t('Result'). '</b> : '. $result. '</li>
    <li><b>'. t('Error'). '</b> : '. $answer['error']. '</li>
    <li><b>'. t('Error N°'). '</b> : '. $answer['errno']. '</li>
  </ul>
</div>
    ';
  }
  return $output;
}

function theme_d4os_io_osservices_wrongbutton() {
  $output = '<div class="messages warning">'. t('Oops...I have pushed the wrong button...'). '</div>';
  return $output;
}
