<?php

/**
 * @package    d4os ui uuid field texture formatter
 * @copyright Copyright (C) 2014 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license   GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * d4os ui uuid field texture formatter is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

 /**
 * Implements hook_field_formatter_info().
 */
function uuid_field_texture_formatter_field_formatter_info() {
  return array(
    'uuid_field_texture_formatter' => array(
      'label' => t('Displays an uuid as a texture'),
      'field types' => array('uuid_field'),
      'settings'  => array(
        'pic_width' => '512',
        'pic_ratio' => '_4_3'
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function uuid_field_texture_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //This gets the actual settings
  $settings = $display['settings'];
  //Initialize the element variable
  $element = array();
  //Add your select box
  $element['pic_width'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Image Width'),
    '#description'    => t('Enter the width of image'),
    '#default_value'  => $settings['pic_width'],
  );
  $element['pic_ratio'] = array(
    '#type'           => 'select',
    '#title'          => t('Image Ratio'),
    '#description'    => t('Select what ratio of image'),
    '#default_value'  => $settings['pic_ratio'],
    '#options'        => array(
      '_4_3' => '4/3',
      '_16_9'  => '16/9',
      '_1_1' => '1/1'
    ),
  );
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function uuid_field_texture_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a @size width texture as an image with a @ratio ratio"', array(
    '@size' => $settings['pic_width'],
    '@ratio' => $settings['pic_ratio']
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function uuid_field_texture_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] == 'uuid_field_texture_formatter') {
    return uuid_field_texture_formatter_format($items, $display);
  }
}

function uuid_field_texture_formatter_format($items, $display) {
  global $base_url;
  $height = $display['settings']['pic_width'];
	switch ($display['settings']['pic_ratio']) {
	  case '_4_3':
	    $height = ($display['settings']['pic_width'] / 4)*3;
	    break;
	  case '_16_9':
	    $height = ($display['settings']['pic_width'] / 16)*9;
	    break;
	}
	$size = 'width="'. $display['settings']['pic_width']. 'px" height="'. $height. 'px"';
	$element = array();
  foreach ($items as $delta => $item) {
    $element[$delta] = array(
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => array(
        'class' => $display['settings']['pic_width']
      ),
      '#value' => '<img class="'. $display['settings']['pic_ratio']. '" src="'. variable_get('d4os_default_asset_pictures_server_url', $base_url . '/asset.php?id=').$item['uuid_field']. '" '. $size.' />'
    );
  }
  return $element;
}

