<?php
/**
* @package    d4os
* @copyright  Copyright (C) 2010 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
* @license    GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
* D4os is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/

// TODO : see what we can do with : http://domain.com:9000/SStats/

function d4os_ui_stats_status_menu() {
  $items = array();
  $items['grid/stats/status'] = array(
    'title'             => 'Status',
    'description'       => 'Check if the grid is online.',
    'page callback'     => 'd4os_ui_stats_status_js',
    'access callback'   => TRUE,
    'type'              => MENU_CALLBACK,
  );
  return $items;
}

function d4os_ui_stats_status_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();
  switch ($op) {

    case 'list':
      $block['grid_status']["info"] = t('Grid status');
      break;

    case 'view':
      switch ($delta) {
        case 'grid_status':
          $content = d4os_ui_stats_status_display();
          $block['subject'] = t('Grid status');
          $block['content'] = $content;
          break;
      }
      break;

    case 'configure':
      switch ($delta) {
        case 'grid_status':
          return d4os_ui_stats_status_params_form();
          break;
      }
      break;
      
    case 'save':
      switch ($delta) {
        case 'grid_status':
          d4os_ui_stats_status_params_save($edit);
          break;
      }
      return;
      break;
  }
  return $block;
}

function d4os_ui_stats_status_params_form() {
  global $grid_url;
  $url = $grid_url. '/simstatus/';
  $form = array();
  $form['d4os_ui_stats_status_url'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Status url'),
    '#description'    => t('Use the url to get the info from.'),
    '#default_value'  => variable_get('d4os_ui_stats_status_url',  $url),
  );
  $form['d4os_ui_stats_status_value'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Value returned'),
    '#description'    => t('Enter the value of the body response.'),
    '#default_value'  => variable_get('d4os_ui_stats_status_value',  'OK'),
  );
  $form['d4os_ui_stats_status_timer_fieldset'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Timer'),
    '#collapsible'  => TRUE,
    '#collapsed'    => FALSE,
  );
  $form['d4os_ui_stats_status_timer_fieldset']['d4os_ui_stats_status_use_timer'] = array(
    '#type'           => 'checkbox',
    '#default_value'  => variable_get('d4os_ui_stats_status_use_timer', 1),
    '#title'          => t('Use timer.'),
    '#description'    => t('Check this option if you want to use a timer to refresh automatically the status on the web page.'),
  );
  $form['d4os_ui_stats_status_timer_fieldset']['d4os_ui_stats_status_timer'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Timer'),
    '#size'           => 5,
    '#maxlength'      => 5,
    '#default_value'  => variable_get('d4os_ui_stats_status_timer', 15),
    '#description'    => t("Enter the value (in seconds) for the timer to refresh the status."),
  );
  return $form;
}

function d4os_ui_stats_status_params_save($edit) {
  variable_set('d4os_ui_stats_status_url',             $edit['d4os_ui_stats_status_url']);
  variable_set('d4os_ui_stats_status_value',           $edit['d4os_ui_stats_status_value']);
  variable_set('d4os_ui_stats_status_use_timer',       $edit['d4os_ui_stats_status_use_timer']);
  variable_set('d4os_ui_stats_status_timer',           $edit['d4os_ui_stats_status_timer']);
}

function d4os_ui_stats_status_display($load_js=TRUE) {
  global $grid_url, $base_url;
  // get the grid status
  $url = $grid_url. '/simstatus/';
  $response = drupal_http_request(variable_get('d4os_ui_stats_status_url',  $url));
  $online = FALSE;
  if ($response->code != 200) {
    $online = FALSE;
  }
  if (strtolower($response->data) == 'ok') {
    $online = TRUE;
  }
  // add the login uri
  $loginuri = variable_get('d4os_default_login_uri', $base_url). ':'. variable_get('d4os_default_login_port', '8002');
  // build the output
  $output = theme('d4os_ui_stats_status', $online, $loginuri);
  if (variable_get('d4os_ui_stats_status_use_timer', 1)) {
    if ($load_js) {
      drupal_add_js(libraries_get_path('jquery.timer').'/jquery.timer.js');
      $js_vars = array(
        'timer'  => variable_get('d4os_ui_stats_status_timer', 15),
      );
      drupal_add_js(array('d4os_ui_stats_status' => $js_vars), 'setting');
      drupal_add_js(drupal_get_path('module', 'd4os_ui_stats_status').'/js/d4os_ui_stats_status.js', 'module', 'footer');
    }
  }
  return $output;
}

function d4os_ui_stats_status_js() {
  echo d4os_ui_stats_status_display(FALSE);
}

function d4os_ui_stats_status_theme() {
  return array(
    // status
    'd4os_ui_stats_status' => array(
      'arguments' => array('online' => FALSE, 'loginuri' => NULL),
    ),
  );
}

function theme_d4os_ui_stats_status($online, $loginuri) {
  // TODO : see the loginuri with counter
  $output = '';//'<div><dl><dt>'. t('Login uri'). '</dt><dd>'. $loginuri. '</dd></dl></div>';
  if ($online) {
    $output .= '<div id="grid_status" class="messages status">'. t('Online'). '</div>';
  }
  else {
    $output .= '<div id="grid_status" class="messages error">'. t('Offline'). '</div>';
  }
  return $output;
}